### ISSUE TITLE
ValueCAN 3 Device LEDs may fail to indicate the correct status

### ISSUE THREAD

**Issue by hollinsky-intrepid** [intrepidcs/libicsneo#16]
See issue https://github.com/intrepidcs/intrepid-socketcan-kernel-module/issues/6

**Comment by tysonite** [comment]
Hi @hollinsky-intrepid, it would be nice if you can look into this issue. The fix can help us to properly debug / observe any issues with the device.

**Comment by hollinsky-intrepid** [comment]
Hi @tysonite, I found and fixed the issue. The fix is in libicsneo v0.1.2 (now on master). I've also updated [icsscand](https://github.com/intrepidcs/icsscand) to use the new libicsneo, and the software version for that is v2.0.2 (now on master in that repo). The kernel module is unchanged.

You should be able to run `git pull` then `git submodule update` within your copy of the icsscand source to pull these updates.

Let us know if you need anything else!
