### ISSUE TITLE
Transmit Report

### ISSUE THREAD

**Issue by pierreluctg** [intrepidcs/libicsneo#28]
Using transmit reports is impossible since the DescriptionID field is missing.

Looks like that the description field (https://github.com/intrepidcs/libicsneo/blob/master/include/icsneo/communication/message/message.h#L17) is never used.

From https://cdn.intrepidcs.net/support/neoVIDLL/TxMessages.htm:

> **Transmit Report**
> 
> After the messages has been transmitted there will be a transmit report message returned from the device. The transmit report will be read out with GetMessages. Any message read which has the SPY_STATUS_TX_MSG (icsSpyStatusTx) bit set in the status bitfield is a transmit report. 
> 
> You can also identify a particular transmitted message with DescriptionID field. This two byte field (only 14 bits are used)  allows the programmer to assign an arbitrary number to a message. This number is then returned in the transmit report.
> 
> The transmit report does not necessarily mean the message was transmitted successfully. For example, the Ford SCP network will return a Transmit Report if it had tried to send a message. Therefore, the programmer should always check the GlobalError Flag in the status bitfield.
> 
> To transmit different messages, set the appropriate bits in the status bitfields. For example, there are bits for init waveforms, extended identifiers and remote frames.

**Comment by hollinsky-intrepid** [comment]
Hi Pierre,

The transmit reports are handled properly within the main APIs (C++ and C). I can see it's not currently implemented in the legacy API during the conversion, perhaps this is what you're referring to?

All the best,
Paul

**Comment by pierreluctg** [comment]
Sorry @hollinsky-intrepid, yes my issue is related to the legacy API.

**Comment by pierreluctg** [comment]
Hi @hollinsky-intrepid, can you provide us with an ETA for this?
Or are you looking for contributors to provide this feature?

**Comment by hollinsky-intrepid** [comment]
Hi @pierreluctg,

We have an MR ready for this, I just need to test it and merge it in. I'll do that today.

--Paul

**Comment by pierreluctg** [comment]
Thank you Paul

**Comment by hollinsky-intrepid** [comment]
You should be all set with the latest changes, let us know if you need anything more!
