### ISSUE TITLE
Qt CAN-BUS plugin + mapping channel/network number to Network::NetID enum. 

### ISSUE THREAD

**Issue by 3electrons** [intrepidcs/libicsneo#33]
Hello, I have experimentally added Qt CAN-BUS plugin for libicsneo [qticsneo](https://github.com/3electrons/qticsneo)

I have ValueCan4 and ValueCan4 Industrial adapters - both support 2 networks  CAN1 and CAN2 what I believe is called channels or networks as it is called in nomenclature you are using (I am one week-old into CAN-BUS at all - so forgive me my lack of knowledge).

Channels are not supported at the moment in the plugin. 

I can get number of channels by: 
`int channels = device->getNetworkCountByType(icsneo::Network::Type::CAN); `
However I am not sure how can I map channel number to respective NetID value. 
 
Is there any method in API to convert channel number as integer {1,2,3... x} to CAN1, CAN2, CAN3 .. CANx? 

I am looking for something like: 
```
Network::getNetworkNo( icsneo::Network::Type::CAN, 0) == Network::NetID::HSCAN1; 
Network::getNetworkNo( icsneo::Network::Type::CAN, 1) == Network::NetID::HSCAN2;  
...
Network::getNetworkNo( icsneo::Network::Type::CAN, 6) == Network::NetID::HSCAN7;  
```

I want to use it to distinguish how to route messages to each interface object (QCanBusDevice) representing single channel/network from message callback. As current libicsneo approach seems to use the same device (icsneo::Device) and single callback to manage all messages regardless of network/channel number.

**Comment by hollinsky-intrepid** [comment]
I believe the function you're looking for is `Device::getNetworkByNumber`. It is a member function of the Device as the networks on each device can be different. Also note that it starts at 1, so `device->getNetworksByNumber(icsneo::Network::Type::CAN, 1) == Network::NetID::HSCAN`

**Comment by 3electrons** [comment]
It works :)
