### ISSUE TITLE
Will this libraries support CAN3 also?

### ISSUE THREAD

**Issue by Elsaligi** [intrepidcs/libicsneo#41]
Hi,

I was doing implementation libicsneo on raspberrypi and followed procedure:
https://medium.com/intrepidcontrolsystems/the-easy-way-to-program-valuecan-4-in-python-using-raspberry-pi-linux-68d160d511ef

Will it support CAN3 devices also?My CAN3 device is not responding . This is the device link i used.
https://store.intrepidcs.com/valuecan3-dw-2-channel-p/vcan-dw3.htm

However muy CAN4 device is responding.

Please Anybody worked with CAN3 with this library ? 
Will library support CAN3?

Please let me know.

Regards,

Elsa

**Comment by hollinsky-intrepid** [comment]
Hi Elsa,

ValueCAN 3 is fully supported.

This can happen if the permissions are not set properly for it. To see if that's the issue, try running your test program with `sudo`. If that's the problem, we can help fix the permissions so that normal users can run it in the future.

All the best,
Paul
