### ISSUE TITLE
ValueCAN4 Industrial and Fire2: loopback testing over ethernet fails, looses messages, has poor performance (icsneo40.dll works well)

### ISSUE THREAD

**Issue by markmenge** [intrepidcs/libicsneo#42]
Summary

Send message commands over ethernet to ValueCAN4 Industrial produce warnings about bytes discarded, exhibits poor performance, unexpected responses.

I am doing loopback testing over wpcap.dll with VSpy3 3.9.6.7, with ValueCAN-4 Industrial, libicsneo from github and it has these problems:
1. When it transmits a message it produces complaints in VSpy3:
    "Critical	neoVI host to device byte(s) discarded	The neoVI discarded at least one byte because it wasn't found in a proper packet"
 
2. It gets messages from undocumented network type 52.

3. Looking at Wireshark, I see the message to transmit a message for Protcol 0xcab1 (transmit to device) for icsneolegacy.dll vs icsneo40.dll is different. icsneolegacy.dll uses icsneocpp library, so I think it affects everyone.

To reproduce:
1. Configure your ValueCan4 Industrial or Fire2 to have ethernet enabled. Wire the buses together in a loopback fashion, HS1 to MS, HS2 to HS3, HS4 to HS5, HS6 to HS7.

2. get and build (using Visual Studio's own CMake) https://github.com/markmenge/libicsneo

3. Run examples/cpp/loopback/libicsneocpp-loopback-example.exe

4. Select icsneolegacy.dll, open a device, send a message, look at VSpy3. It complains of discarded bytes.  (seems ok when you use icsneo40.dll)

5. Run a loopback test (eg M), notice it has bad performance and produces errors with icsneolegacy.dll. icsneo40.dll works well.

**Comment by hollinsky-intrepid** [comment]
Part of the problem will come from the fact that both Vehicle Spy 3 and libicsneo will be trying to talk to the device at the same time. This is not yet supported, whereas icsneo40.dll can negotiate this through the use of neoVI Server.

Perhaps if I could understand more about your use case, I could assist further to that end. If you'd prefer to speak one on one, you could contact our support and they'll put you in touch.
