### ISSUE TITLE
Master does not build in x86 Mode for Windows (MSBuild) -  '__unaligned' keyword not supported on this architecture

### ISSUE THREAD

**Issue by dan5912** [intrepidcs/libicsneo#44]
Building the libicsneo main cmake project under msvc-x86 results in:
error C4235: nonstandard extension used: '__unaligned' keyword not supported on this architecture

Best I can tell, __unaligned is not supported under x86 and should be switched out under that platform
https://docs.microsoft.com/en-us/cpp/cpp/unaligned?view=msvc-170

**Comment by hollinsky-intrepid** [comment]
Fixed! I've added x86 to our CI so that it won't break like this in the future. Thanks for the heads up!
