### ISSUE TITLE
Please expose GetTimeStampForMsg in the legacy API

### ISSUE THREAD

**Issue by pierreluctg** [intrepidcs/libicsneo#5]

**Comment by pierreluctg** [comment]
Hi @drebbe-intrepid, let me know if there is anything I can do to get this in.

Thank you

**Comment by drebbe-intrepid** [comment]
@pierreluctg Let me see what I can do here.

**Comment by drebbe-intrepid** [comment]
@pierreluctg `icsneoGetTimeStampForMsg` is not currently implemented. I'm looking into the details now.

**Comment by drebbe-intrepid** [comment]
@pierreluctg I should have something available for you either late tomorrow or Monday.

**Comment by pierreluctg** [comment]
Thank you @drebbe-intrepid

**Comment by hollinsky-intrepid** [comment]
Merged pull request #8
