### ISSUE TITLE
icsneoSetRTC removed but still defined in python_ics

### ISSUE THREAD

**Issue by jazi007** [intrepidcs/libicsneo#54]
According to the documentation of python_ics: https://python-ics.readthedocs.io/en/master/#ics.ics.set_rtc

this method needs `icsneoSetRTC` but this function does not existe anymore.

to synchronize ICS HW with others this function is needed

**Comment by kschwarz-intrepidcs** [comment]
RTC functions have been added with https://github.com/intrepidcs/libicsneo/commit/b3bbf91e8cc5c902d1347986017397ab990858d4
