### ISSUE TITLE
Clarify epoch for timestamp

### ISSUE THREAD

**Issue by cconverse711** [intrepidcs/libicsneo#57]
From what I can tell in observing `icsneoGetTimeStampForMsg`, it uses a different epoch than the traditional Linux epoch (Jan 1 1970) and instead uses Jan 1 2007. Is this correct and/or is this officially documented anywhere?

**Comment by drebbe-intrepid** [comment]
@cconverse711 1/1/2007 is our epoch time, I'm not sure if its documented anywhere but it comes from the firmware level.

**Comment by kschwarz-intrepidcs** [comment]
As @drebbe-intrepid mentioned 1/1/2007 is the ICS epoch and is correct for the return from `icsneoGetTimeStampForMsg()`.
