### ISSUE TITLE
Please expose ValidateHObject in the legacy API

### ISSUE THREAD

**Issue by pierreluctg** [intrepidcs/libicsneo#7]

**Comment by pierreluctg** [comment]
Hi @drebbe-intrepid, let me know if there is anything I can do to get this in.

Thank you

**Comment by drebbe-intrepid** [comment]
@pierreluctg Let me see what I can do here.

**Comment by drebbe-intrepid** [comment]
@pierreluctg `icsneoValidateHObject` seems to already be exposed in the legacy API.  Can you provide more detail here?

**Comment by pierreluctg** [comment]
@drebbe-intrepid, you are right, this issue is invalid.
